spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vacancies
    username: postgres
    password: root

server:
  port: 8081

DOU_URL: 'https://jobs.dou.ua/'
DJINNI_URL: 'https://djinni.co/jobs/'